sudo: required
services:
  - docker

before_install:
  - docker build -t haavrilyars/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true haavrilyars/react-test npm test -- --coverage

after_success:
  - docker build -t haavrilyars/multi-client ./client
  - docker build -t haavrilyars/multi-nginx ./nginx
  - docker build -t haavrilyars/multi-server ./server
  - docker build -t haavrilyars/multi-worker ./worker

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push haavrilyars/multi-client
  - docker push haavrilyars/multi-nginx
  - docker push haavrilyars/multi-server
  - docker push haavrilyars/multi-worker