sudo: required
services:
- docker
before_install:
- docker build -t haavrilyars/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true haavrilyars/react-test npm test -- --coverage
after_success:
- docker build -t haavrilyars/multi-client ./client
- docker build -t haavrilyars/multi-nginx ./nginx
- docker build -t haavrilyars/multi-server ./server
- docker build -t haavrilyars/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push haavrilyars/multi-client
- docker push haavrilyars/multi-nginx
- docker push haavrilyars/multi-server
- docker push haavrilyars/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-356713479470
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: "RefDUWVglZvO+A+TjNCPSXYvjOBTVJQN3j1K3mkE6VFoYUIKcnoSlTZakflSqm5lSA98mSEUlPaInskiDVPDnqBVwPYPaPTJbVd/9wbB5BwPr+3Lm0T3X0F7SLqmqZYenSvxG8GIHUD9hTtV4UrFM4L/imSSenRypHl/PuQcGQDvPFJjoisVXH5hVBkXjNVP369GJTrQ0YVU4+CLxHznx4VRuuSxC6QZLA5TB1Gfnw3H+2mJwK+CQlE5pZpMIILGc89gRJDFo3JG/nVV3U1RJA0oWVwERJwHd367lu/QBPNz/QwkM3JGY15oGfmNeTfofb4cVo9Z2vj5HHbpH1082ZbIsPHHHSgPNHVB/HgXZzftmo3We2idK89oa/l6aWOuCeS+eUKewUMyHixl2U6MYVjcNqvJAtW5Hacp5UfRQVClKcf8HkY7VnNDuajRMuQEhMI3fKANiJK896k2PhmQSkWnUWI0LbYUmPHN2CnFF4KzQcO5PTsr3y0UkI8FNmZUHfiHpiVanlG86vlLCyk/kOzYUzPcxSXzp/muxo7RwTdvYHg60Ws/iMpdkJCm8IELRFsQfs8ycUK28DiCR6n4rmTMuRcHZ591/K+CsyW36ZPX7dJf+XuXPSlMFuru9yWMTmgazUkWuWaFMVaIrEE1Qt5Emjq32g2Wrsr8KoDjpd4="
  secret_access_key:
    secure: "Txg4BAFIGKouGON/q8Ec0Z1E1lPe+O/ululVVukJ3++cDiLLJ3VjQ4WXWKqZFl6Ou8L+OZ9zs5zg28gpH1m3btGHLclfUnmOEHiqarD2gPJ1X3xEcszHFAwg6D83IJoK9739RnSgHpojVQjSLXTFv4Iz+s2umoQ8dMinsiZVX8I35mXD1KA5gFZo3mqdXXNSHn242xAT955benV9pETDtoB6FAOjJbw7KUIEyZgbbq9vaFSXi5GKh50+AeVoYivssd3UXoVOImNKsQ6QbHZ4/l2xUaZqU1ZOhFjOHA3jEq6J/NkcKCtWA6wMwGYYzkvAQbZzDjpnxQFD0pNOk48n2OJXGS0ljTqlitouyBKJIfQHHKLY8grPrKPY/BOyOAx1JP+9KakQYl0yGizK8oCD/8WaNMnLugLluFdLWnOPGzAfTRYANFmJ3qcRD9PdDLCI11S5ArYZomfg1WosnldpYT1Jk+GSzNoSAEAceS2XbwKfcwprRCPJtCS5u+6RrFF3TSH9q+OkOvaOG0Cf9PagBYaUXVfSIxea1sNXFuCPocFxbUPP38u0HGFgdqBwwHnO3HasibB9H7/ZqHLB4nwhbWF5/ybzovizgs+EJQoOJu2NcMJDXJa8eRyq0UAbDy8GzuYIxo/Qmt4H8ieh4QXC3AV38Fn04IPW5JE813dWwAg="