sudo: required
services:
- docker
before_install:
- docker build -t haavrilyars/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true haavrilyars/react-test npm test -- --coverage
after_success:
- docker build -t haavrilyars/multi-client ./client
- docker build -t haavrilyars/multi-nginx ./nginx
- docker build -t haavrilyars/multi-server ./server
- docker build -t haavrilyars/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push haavrilyars/multi-client
- docker push haavrilyars/multi-nginx
- docker push haavrilyars/multi-server
- docker push haavrilyars/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-356713479470
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"