sudo: required
services:
- docker
before_install:
- docker build -t haavrilyars/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true haavrilyars/react-test npm test -- --coverage
after_success:
- docker build -t haavrilyars/multi-client ./client
- docker build -t haavrilyars/multi-nginx ./nginx
- docker build -t haavrilyars/multi-server ./server
- docker build -t haavrilyars/multi-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push haavrilyars/multi-client
- docker push haavrilyars/multi-nginx
- docker push haavrilyars/multi-server
- docker push haavrilyars/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-356713479470
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: "X+XMpBpbd7NkDud6jxxGOfMKl0YfZQg/bFtsaNbi7q19A/dgPAqq8L5OminTLByqZ5gbzgQrRca3myQVb/gsfqfy9FPcRaJPpwkmSDyzAHykFpmbvAkraZV9Ir/5C16lOEYxKfoNOGXnoE1yq2Q8NrdYAIjQMQX4IwyP5K8EtHmHG21tBIcPVuM9f5je51pdy695+B22gup/YjRpcvqjH9Aq3EoTO6pR8PBWTjPU9Ox2puOC6nYo5YniVgBgh/eIk9u6g5sOkHBpD+8ce0cE/+9PUmDVtcQOWXBfAngrXJGVARGUmTcCwdjiFtMb8COFD18itQWtuzdY7RyRE19dCn8H+QATYf1K2NxIoF5GX11YtNd92dE+JV2aEJFhYlj/uiXhAJavZ4Vahh2XuQwUzYxHkW0mATLcClGEH/zmJ125mErd8Vh1s1Vmhu7agPUmPGP6CSi1nt2UBSB+3LtL//93HHG8JfDJmuWyPURWYP+BMQzAUVf2H323kSokbbsXRXQMuVXcWUXu+GXNjxKaz03cewK8vQW+Uvb67Hh8XW/8A+DgG7ywgzXS2YG7hGGyD8jBBxLwRAS0kKTI1amr8A8yQu+aMu0OP0wviMEaHHWT/PChETrT30dGoNm1dvIJc+wzY1mXrU8nh47x3cG+ckh/QhV2KWZL6IskijSm9oI="
  secret_access_key:
    secure: "mGJayrKFOisJ3+yjwlp/d2IE3MBW9Qy0TJoiFh49HoaEi5Ntkxip5RJWwqQgL4KMRpCw32FIMOpP7y1sx5MX6MOvJT99FQ4x9u1LWotG51VS+mTJ5oWRe4BxXAM4Mkbg+Qanvd57iBDTPVZgLmjWdsA1Ozq87hJ6DTwZFhQmQHPjmK+PSe2LDpH/ehSW54Ysquu3p+tEG/Il6pVARCfoZwahLrvYja3w39emvw1vN/7DzWeqRTHJudkKvMlrNs9cQkwbWOpHTfBX3nY21zppWjxdvsyYvOSN/wBMmFYdQRi2AHMSthzzHMYGqKlFK2tEdh7MYnox+j0fBGLXwTHUbEVFEcA2I6m+9KfOr7G+orRXH6Thwi3hYkYPvCpxh8UrQQacGvGxJWxrJ2kV73rje5kClmnl4ELY+bnJrJQuo1ew1UQzTDgFUd8tbjCjvNVMZfIIlOaGZEnTX0Zjgj5Ohr655wQCCG6CMLmwvzJVQXUiA3tqLpzTSkvRnJFHBkv4sOGFSdSP1Q25NKHeGuzkdCzTTcMcOqm1HwJamZ7hqk8IepwvvTapITrdwfkOGinD3AVDqId8pxPhV37uBP6AYnbMNHnZ0ZJH+YCnizYCuKmTNbTSUsIWLi8vJjVtay1sQ18VeDEvIgSv7OLikDC+/f9aMjVCXe9Qb5ETHTHcsb0="